### ISSUE TITLE
Filter in Router is not working properly

### ISSUE THREAD

**Issue by sanjeevdivekar** [tattersoftware/codeigniter4-visits#28]
Hello,

When I apply a filter to the route it records 2 times visits

$routes->get('/', 'Home::index', ['filter' => 'visits']);

I am using "tatter/visits": "^v2.0" version

I am novice to CodeIgniter.

Regards,

**Comment by MGatner** [comment]
Are the visit records identical? Do you have other filters configured in **app/Config/Filters.php**? Are you using redirects (like "force secure": check your App Config)?

**Comment by sanjeevdivekar** [comment]
No. But when I debug the code, I found VisitsFilter before() and after() functions are calling for same Request.

When I comment $this->record($request); in before() it works perfectly.

**Comment by MGatner** [comment]
Oh yes! That's intentional, because there are some cases where each is better. You should be applying the filter from the Filters Config where you can specify before/after. 

I will think about a library solution for this - maybe offering it as two separate filters would make sense? Or just adding a check so it only records the visit once?

**Comment by sanjeevdivekar** [comment]
Thanks @MGatner.

Any suggestion to exclude /admin section from Visit Records?

**Comment by MGatner** [comment]
Check the User Guide, but you can use the "except" directive:
```php
public $globals = [
        ...
        'after' => [
            'visits' => ['except' => ['admin*']],
        ],
    ];
```

https://codeigniter.com/user_guide/incoming/filters.html#globals

**Comment by sanjeevdivekar** [comment]
Thanks @MGatner.

It solved my problem
