### ISSUE TITLE
How can I store Browser, Mobile and Platform

### ISSUE THREAD

**Issue by sanjeevdivekar** [tattersoftware/codeigniter4-visits#29]
Hello,

I have successfully implemented transformer, But how can I store Browser, Mobile and Platform in Visit Entity.

Can you guide me how to extent Visits Entity and Model to store additional Data?

Regards,

**Comment by MGatner** [comment]
Make a migration to add the desired filters to your database (`visits` table). Then all you need to do is creat **app/Models/VisitModel.php** that extends this package's class. You can add allowed fields, extend any behavior, and set the return type to your own Entity.

**Comment by sanjeevdivekar** [comment]
Can you explain a bit more? or provide Sample Code. I tried but failed.

**Comment by MGatner** [comment]
I cannot write this code for you. Migrations are well documented. If you want some examples of using migrations in your project to supplement library tables and using an extended model: go check out CodeIgniter Shield where there are lots of docs and examples.

**Comment by sanjeevdivekar** [comment]
It's not about Migration. My modified entity is not saving in the database.


Here is my VisitsTransformer.php
```
namespace Webly\Core;

use Tatter\Visits\Interfaces\Transformer;
use CodeIgniter\HTTP\IncomingRequest;
use Tatter\Visits\Entities\Visit;

class VisitsTransformer implements Transformer
{

    public static function transform(Visit $visit, IncomingRequest $request): ?Visit
    {
        $agent = $request->getUserAgent();

        if ($agent->isBrowser()) {
            $currentAgent = $agent->getBrowser() . ' ' . $agent->getVersion();
        } elseif ($agent->isRobot()) {
            $currentAgent = $agent->getRobot();
        } elseif ($agent->isMobile()) {
            debug($agent->getMobile());
            $currentAgent = $agent->getMobile();
        } else {
            $currentAgent = 'Unidentified User Agent';
        }

        $visit->platform = $agent->getPlatform();
        
        return $visit;
    }
}
```
And this is my VisitModel.php
```
namespace Webly\Core\Models;

use CodeIgniter\HTTP\IncomingRequest;
use CodeIgniter\I18n\Time;
use CodeIgniter\Model;
use Faker\Generator;
use Webly\Core\Entities\Visit;

class VisitModel extends Tatter\Visits\Models\VisitModel
{
    protected $returnType    = Visit::class;
    
   protected function initialize()
   {
        $this->allowedFields[] = [
            'browser',
            'mobile',
            'platform'
        ];
   }    
}
```
Thanks again for replying my silly question

**Comment by MGatner** [comment]
That all looks correct to me! I see your `debug()` in there: you've confirmed your transformer is actually running?

And just to be *super* sure: you've already added `platform` to your database `visits` table?

**Comment by sanjeevdivekar** [comment]
Yes. The transformer is working Perfect. 
debug() is my own global function to display data like print_r().
But I am confused with line no 103 in VisitsFilter.php. save() functions is using Tatter\Visits\Models\VisitModel.
One more question. Do I need to use my Own entity or I can use Tatter\Visits\Entities\Visit ?

**Comment by MGatner** [comment]
The Filter uses `model()` which locates the class using Factories (see: https://codeigniter.com/user_guide/concepts/factories.html#model). This means if you have a model of the same name in **app/Models/** then that will be returned instead of the library's native one. It would be a good next thing to confirm; add `debug(get_class($this->model))` and see which model is actually in use.

**Comment by sanjeevdivekar** [comment]
Mystery Solved.
Thanks for explaining.

As you see I am developing Vendor Plugin. Is there any way to use Visit Plugin in another Plugin ?
Something like CodeIgniter/Shield allow to use our own User Model.

**Comment by MGatner** [comment]
Ohhh gotcha! In other words: your VisitModel is also in a third-party namespace. In that case it won't be given preference by default. What you could do is "seed" the Factory with your model - generally not a great option because then developers using your plugin cannot provide their own version in App anymore, but that might be an acceptable limitation. 
```php
$visitsModel = new \Foo\Bar\VisitsModel();
Factories::injectMock('models', 'VisitModel', $model);
```
In order to get this in before the filter probably the best place to put it would be in **src/Config/Events.php** and have it fire on `pre_system`. 

I would also accept a Pull Request to add a Config value for the model to use, like Shield.
